### ISSUE TITLE
calculate difference between input and output deltas

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/multibind#8]
For diagnostics we would like to see how much the MLE procedure shifts deltas. 
* compute final minus initial for each delta (DG and pKa)
* make available in data structure for analysis/plotting
* ideally, create a nx graph with the deltas on the edges for visualization

**Comment by orbeckst** [comment]
from a discussion with @VOD555

**Comment by ianmkenney** [comment]
@orbeckst @VOD555 The `Multibind` class now has the `deltas` attribute after the `MLE` method is run. This is an `(N, N)` array where elements at index `[i,j]` are the input free energy differences between states `i` and `j` (`np.nan` indicates that the edge was not defined by the user). These are all in kT and have already taken into account the pKa -> dG calculation. The `dGs` array is also stored, which gives easier access to the computed free energy difference from the MLE method. The "final minus initial" should just be `c.dGs - c.deltas`. 

The `MultibindScanner` has these matrices as functions of ligand concentrations in the `results.deltas` and `results.dGs` attributes.

**Comment by ianmkenney** [comment]
These features have been merged into develop

**Comment by orbeckst** [comment]
Sounds good. Just make sure that the documentation makes clear what `deltas` is. I first though these would be the *differences* themselves.

**Comment by ianmkenney** [comment]
@orbeckst I updated the docstrings to clarify that. Closing
