### ISSUE TITLE
error estimates

### ISSUE THREAD

**Issue by orbeckst** [Becksteinlab/multibind#9]
Provide error estimate on computed quantities
- G_i
- k_ij

Possibly use Cramer-Rao.

**Comment by ianmkenney** [comment]
### G_i errors

The covariance matrix is now accessible through the `Multibind` class after the `MLE` method is invoked though the `covariance_matrix` attribute. In the case of the `MultibindScanner`, after invoking `run`, the concentration dependent covariance matrix can be accessed using the `results.covariance` attribute.

### k_ij errors

The `multibind.nonequilibrium.rate_matrix` method now returns `(Multibind, rate_matrix, rate_matrix_standard_error)`. The last element of the return is a `(N, N)` array where each element at index `[i,j]` is the standard error of the projected rate `k_ij`

**Comment by orbeckst** [comment]
Having the covariance matrix is good but as a user I shouldn't need to pull error estimates out of them. Can you add a (maybe managed/property) attribute that mirrors the way you access the G_i but that's just named something like Gi_standard_error?

**Comment by ianmkenney** [comment]
@orbeckst I just added another attribute that stores the standard errors directly: `Multibind.std_errors`.

**Comment by orbeckst** [comment]
good!
